"""Dockerfile, requirements.txt, and .dockerignore contract for identity-normalization."""

# third-party
import pytest

from tests.helpers import REPO_ROOT

SERVICE_DIR = REPO_ROOT / "services" / "identity-normalization"
DOCKERFILE_PATH = SERVICE_DIR / "Dockerfile"
# requirements.in holds the declared floors; requirements.txt is the pip-compiled
# lock generated from it plus shared/pyproject.toml (see
# DEPENDENCIES.md).
REQUIREMENTS_IN_PATH = SERVICE_DIR / "requirements.in"
REQUIREMENTS_PATH = SERVICE_DIR / "requirements.txt"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _dockerfile_text() -> str:
    """Return Dockerfile content. Fails the calling test if absent."""
    if not DOCKERFILE_PATH.exists():
        pytest.fail(
            f"Dockerfile not found at {DOCKERFILE_PATH}. "
            "The implementer must create services/identity-normalization/Dockerfile."
        )
    return DOCKERFILE_PATH.read_text(encoding="utf-8")


def _requirements_text() -> str:
    """Return requirements.txt (compiled lock) content. Fails if absent."""
    if not REQUIREMENTS_PATH.exists():
        pytest.fail(
            f"requirements.txt not found at {REQUIREMENTS_PATH}. "
            "Regenerate the lock from requirements.in — see "
            "DEPENDENCIES.md."
        )
    return REQUIREMENTS_PATH.read_text(encoding="utf-8")


def _requirements_in_text() -> str:
    """Return requirements.in (declared floors) content. Fails if absent."""
    if not REQUIREMENTS_IN_PATH.exists():
        pytest.fail(
            f"requirements.in not found at {REQUIREMENTS_IN_PATH}. "
            "The service's declared dependency floors live here."
        )
    return REQUIREMENTS_IN_PATH.read_text(encoding="utf-8")


def _requirements_in_lines() -> list[str]:
    """Return non-comment, non-empty lowercased lines from requirements.in."""
    content = _requirements_in_text()
    return [
        line.strip().lower()
        for line in content.splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


# ===========================================================================
# CLASS 1 — requirements.txt
# ===========================================================================


class TestRequirementsTxt:
    """Service deps split into floors and a lock (ADR-0012):
    requirements.in declares the four service-direct floors (fastapi, uvicorn,
    python-ldap, pyyaml) — data-layer deps belong to naas_shared and must NOT be
    duplicated there. requirements.txt is the pip-compiled lock; it deliberately
    pins the FULL transitive closure (including shared's sqlalchemy/asyncpg/redis)
    so the image install is reproducible. The Dockerfile installs the lock, then
    naas_shared editable with --no-deps.
    """

    def test_requirements_in_exists(self) -> None:
        """requirements.in (the declared floors) must exist.

        WHY: It is the pip-compile input; the lock is generated from it. Without it
        the lock cannot be regenerated when a floor changes.
        """
        assert REQUIREMENTS_IN_PATH.exists(), (
            f"requirements.in not found at {REQUIREMENTS_IN_PATH}. "
            "The service's declared dependency floors live here."
        )

    def test_requirements_txt_exists(self) -> None:
        """requirements.txt (the lock) must exist at services/identity-normalization/.

        WHY: The Dockerfile copies this file and runs `pip install -r` on it.
        Without it, the image build fails at the COPY/RUN step.
        """
        assert REQUIREMENTS_PATH.exists(), (
            f"requirements.txt not found at {REQUIREMENTS_PATH}. "
            "Regenerate the lock from requirements.in — see "
            "DEPENDENCIES.md."
        )

    def test_requirements_txt_is_compiled_lock(self) -> None:
        """requirements.txt must be a pip-compiled lock, not a hand-edited list.

        WHY: ADR-0012 requires the install artifact to be the generated lock. The
        pip-compile header marks it as such and records the regenerate command.
        """
        assert "autogenerated by pip-compile" in _requirements_text(), (
            "requirements.txt must be generated by pip-compile (its header should "
            "say so). Regenerate it from requirements.in + shared/pyproject.toml — "
            "see DEPENDENCIES.md."
        )

    def test_requirements_in_lists_fastapi(self) -> None:
        """requirements.in must declare fastapi (any version specifier or bare name).

        WHY: fastapi is the web framework for the /health endpoint; it is a
        service-direct dependency and must be declared in the floors, not relied on
        transitively. Spec §5.8 names it explicitly.
        """
        lines = _requirements_in_lines()
        fastapi_lines = [line for line in lines if line.startswith("fastapi")]
        assert fastapi_lines, (
            f"requirements.in must list 'fastapi' (with or without version pin). "
            f"Found lines: {lines}"
        )

    def test_requirements_in_lists_uvicorn(self) -> None:
        """requirements.in must declare uvicorn (with or without [standard] extra).

        WHY: uvicorn is the ASGI server. The Dockerfile CMD is 'uvicorn app.main:app
        --port 8002'. If uvicorn is absent from the floors the lock won't pin it and
        the CMD fails with 'command not found'.
        """
        lines = _requirements_in_lines()
        uvicorn_lines = [line for line in lines if line.startswith("uvicorn")]
        assert uvicorn_lines, (
            f"requirements.in must list 'uvicorn' (with or without [standard]). "
            f"Found lines: {lines}"
        )

    def test_requirements_in_lists_python_ldap(self) -> None:
        """requirements.in must declare python-ldap (required for LDAP enrichment).

        WHY: Spec §5.8 — 'python-ldap>=3.4'. python-ldap is the C-extension LDAP
        client used by the LdapEnricher adapter (app/adapters/ldap.py). It is
        service-specific (not a shared dep), so the floor must declare it.
        Note: PyPI name is 'python-ldap'; pip normalizes hyphens to dashes/underscores.
        """
        lines = _requirements_in_lines()
        # Match 'python-ldap', 'python_ldap' — pip normalizes these
        ldap_lines = [
            line
            for line in lines
            if line.startswith("python-ldap") or line.startswith("python_ldap")
        ]
        assert ldap_lines, (
            f"requirements.in must list 'python-ldap' (with or without version pin). "
            f"Spec §5.8. Found lines: {lines}"
        )

    def test_requirements_in_lists_pyyaml(self) -> None:
        """requirements.in must declare pyyaml (required for loading normalization.yaml).

        WHY: Spec §5.8 — 'pyyaml>=6.0'. The composition root loads and validates
        config/normalization.yaml at startup. Without pyyaml in the floors the lock
        won't pin it and the yaml.safe_load call raises ModuleNotFoundError.
        """
        lines = _requirements_in_lines()
        # Match 'pyyaml', 'pyyaml>=...', etc.
        yaml_lines = [line for line in lines if line.startswith("pyyaml")]
        assert yaml_lines, (
            f"requirements.in must list 'pyyaml' (with or without version pin). "
            f"Spec §5.8. Found lines: {lines}"
        )

    def test_requirements_in_does_not_list_sqlalchemy(self) -> None:
        """requirements.in must NOT list sqlalchemy.

        WHY: Data-layer dependencies are owned by naas_shared (shared/pyproject.toml).
        Declaring them in the service floors would create two sources of truth. They
        legitimately appear in the generated lock as part of shared's transitive
        closure — but not as a service-declared floor.
        """
        lines = _requirements_in_lines()
        sqlalchemy_lines = [line for line in lines if line.startswith("sqlalchemy")]
        assert not sqlalchemy_lines, (
            f"requirements.in must NOT declare 'sqlalchemy' — it is owned by "
            f"naas_shared. Found: {sqlalchemy_lines}"
        )

    def test_requirements_in_does_not_list_asyncpg(self) -> None:
        """requirements.in must NOT list asyncpg.

        WHY: asyncpg is the async PostgreSQL driver owned by naas_shared's
        sqlalchemy[asyncio] dependency. Declaring it in the service floors would
        duplicate the source of truth (see sqlalchemy above).
        """
        lines = _requirements_in_lines()
        asyncpg_lines = [line for line in lines if line.startswith("asyncpg")]
        assert not asyncpg_lines, (
            f"requirements.in must NOT declare 'asyncpg' — it is owned by "
            f"naas_shared. Found: {asyncpg_lines}"
        )

    def test_requirements_in_does_not_list_redis_client(self) -> None:
        """requirements.in must NOT list the redis Python client package.

        WHY: redis-py is owned by naas_shared. Declaring it in the service floors
        would duplicate the source of truth.
        """
        lines = _requirements_in_lines()
        redis_lines = [
            line
            for line in lines
            if line == "redis"
            or line.startswith("redis==")
            or line.startswith("redis>=")
            or line.startswith("redis~=")
        ]
        assert not redis_lines, (
            f"requirements.in must NOT declare 'redis' — it is owned by "
            f"naas_shared. Found: {redis_lines}"
        )


# ===========================================================================
# CLASS 2 — Dockerfile
# ===========================================================================


class TestDockerfile:
    """services/identity-normalization/Dockerfile: repo-root context, shared/ first,
    python-ldap system deps before pip, EXPOSE 8002, uvicorn CMD on port 8002.
    """

    def test_dockerfile_exists(self) -> None:
        """Dockerfile must exist at services/identity-normalization/Dockerfile.

        WHY: Without it, docker compose build identity-normalization fails with
        'Dockerfile not found'. This is the path referenced in docker-compose.yml's
        build.dockerfile field.
        """
        assert DOCKERFILE_PATH.exists(), (
            f"Dockerfile not found at {DOCKERFILE_PATH}. "
            "The implementer must create services/identity-normalization/Dockerfile."
        )

    def test_dockerfile_exposes_port_8002(self) -> None:
        """Dockerfile must contain EXPOSE 8002.

        WHY: The spec §5.8 states the port is 8002 (not 8001 — that is event-ingestion).
        The docker-compose.yml maps ${IDENTITY_NORMALIZATION_PORT:-8002}:8002.
        An EXPOSE for the wrong port creates a confusing mismatch and may cause
        the healthcheck to probe the wrong port.
        """
        content = _dockerfile_text()
        lines = [line.strip() for line in content.splitlines()]
        expose_lines = [line for line in lines if line.upper().startswith("EXPOSE")]
        assert any("8002" in line for line in expose_lines), (
            f"Dockerfile must contain 'EXPOSE 8002'. "
            f"Found EXPOSE lines: {expose_lines}. "
            "Port 8002 is the identity-normalization port (not 8001 / event-ingestion)."
        )

    def test_dockerfile_copies_shared_before_service_code(self) -> None:
        """COPY shared/ must appear before COPY services/identity-normalization/app/.

        WHY: Docker layer caching is invalidated by the first COPY that changes, so
        layers must be ordered slowest- to fastest-changing. Under ADR-0012 that
        order is: the lockfile (requirements.txt — changes only on a deliberate
        regenerate) is copied and installed first, then the shared library (copied
        and installed editable), then the service app/ code last (changes most
        often). This test pins the shared-before-app invariant; reversing it would
        rebuild the shared install on every service-code edit.
        """
        content = _dockerfile_text()
        lines = content.splitlines()

        shared_copy_idx = None
        app_copy_idx = None

        for i, line in enumerate(lines):
            stripped = line.strip()
            if (
                stripped.startswith("COPY")
                and "shared/" in stripped
                and shared_copy_idx is None
            ):
                shared_copy_idx = i
            # Match the service *app code* COPY specifically — not the earlier
            # requirements.txt COPY, which legitimately precedes shared/.
            if (
                stripped.startswith("COPY")
                and "identity-normalization/app" in stripped
                and app_copy_idx is None
            ):
                app_copy_idx = i

        assert shared_copy_idx is not None, (
            "Dockerfile must contain a COPY instruction for shared/ "
            "(e.g., 'COPY shared/ /app/shared/'). Not found."
        )
        assert app_copy_idx is not None, (
            "Dockerfile must contain a COPY instruction for the service app code "
            "(e.g., 'COPY services/identity-normalization/app/ ...'). Not found."
        )
        assert shared_copy_idx < app_copy_idx, (
            f"COPY shared/ (line {shared_copy_idx + 1}) must appear BEFORE "
            f"COPY services/identity-normalization/app/ (line {app_copy_idx + 1}). "
            "The shared library changes less often than service code and should be "
            "an earlier layer."
        )

    def test_dockerfile_installs_shared_as_editable_no_deps(self) -> None:
        """Dockerfile must run `pip install -e /app/shared/ --no-deps`.

        WHY: The -e flag installs naas_shared from the COPYed source path, making
        `import naas_shared` resolve inside the container; without it the shared
        source is present but not importable. --no-deps is required under ADR-0012:
        the lockfile installed just before this step already pins shared's full
        transitive closure, so re-resolving shared's dependencies here could pull
        newer versions and defeat the lock.
        """
        content = _dockerfile_text()
        lines = content.splitlines()
        install_lines = [
            line.strip() for line in lines if "pip install" in line and "shared" in line
        ]
        editable_lines = [
            line for line in install_lines if "-e" in line and "shared" in line
        ]
        assert editable_lines, (
            f"Dockerfile must run 'pip install -e /app/shared/ --no-deps' (or "
            f"equivalent). Found install lines referencing shared: {install_lines}. "
            "The -e flag is required so 'import naas_shared' resolves in the container."
        )
        assert all("--no-deps" in line for line in editable_lines), (
            f"The editable shared install must pass --no-deps. Found: {editable_lines}. "
            "Per ADR-0012 the lockfile already pins shared's closure; re-resolving "
            "its deps here would defeat the lock."
        )

    def test_dockerfile_cmd_launches_uvicorn_on_port_8002(self) -> None:
        """Dockerfile CMD must launch uvicorn on app.main:app port 8002.

        WHY: Spec §5.8 — CMD is 'uvicorn app.main:app --host 0.0.0.0 --port 8002'.
        The docker-compose healthcheck probes http://localhost:8002/health. A CMD
        that uses a different port causes the healthcheck to always fail and the
        container to be permanently 'unhealthy'.
        """
        content = _dockerfile_text()
        lines = content.splitlines()
        cmd_lines = [
            line.strip() for line in lines if line.strip().upper().startswith("CMD")
        ]
        assert cmd_lines, (
            "Dockerfile must contain a CMD instruction. "
            f"No CMD found in {DOCKERFILE_PATH}."
        )
        last_cmd = cmd_lines[-1]  # The effective CMD is the last one
        assert "uvicorn" in last_cmd, f"CMD must invoke uvicorn. Got: {last_cmd!r}"
        assert "app.main:app" in last_cmd, (
            f"CMD must reference 'app.main:app' as the ASGI module. Got: {last_cmd!r}"
        )
        assert "8002" in last_cmd, (
            f"CMD must use port 8002. Got: {last_cmd!r}. "
            "The docker-compose healthcheck probes localhost:8002."
        )

    def test_dockerfile_installs_gcc_for_python_ldap(self) -> None:
        """Dockerfile must apt-get install gcc before pip install.

        WHY: Spec §5.8 — 'python-ldap needs system build dependencies: add an
        apt-get install for libldap2-dev, libsasl2-dev, and gcc BEFORE pip install,
        or the build fails compiling python-ldap.' python:3.12-slim has no C compiler.
        Without gcc the python-ldap build fails with 'gcc: command not found'.
        """
        content = _dockerfile_text()
        lower = content.lower()
        assert "gcc" in lower, (
            "Dockerfile must install 'gcc' via apt-get (needed to compile python-ldap). "
            "Spec §5.8: add 'gcc' to the apt-get install list before pip install."
        )

    def test_dockerfile_installs_libldap2_dev_for_python_ldap(self) -> None:
        """Dockerfile must apt-get install libldap2-dev before pip install.

        WHY: Spec §5.8 — libldap2-dev provides ldap.h, the C header for the OpenLDAP
        client library that python-ldap's C extension includes at build time.
        Without it the build fails with 'ldap.h: No such file or directory'.
        """
        content = _dockerfile_text()
        lower = content.lower()
        assert "libldap2-dev" in lower, (
            "Dockerfile must install 'libldap2-dev' via apt-get "
            "(needed to compile python-ldap). "
            "Spec §5.8: add 'libldap2-dev' to the apt-get install list."
        )

    def test_dockerfile_installs_libsasl2_dev_for_python_ldap(self) -> None:
        """Dockerfile must apt-get install libsasl2-dev before pip install.

        WHY: Spec §5.8 — libsasl2-dev provides sasl.h, the C header for SASL
        authentication used by python-ldap. Without it the build fails with
        'sasl.h: No such file or directory'.
        """
        content = _dockerfile_text()
        lower = content.lower()
        assert "libsasl2-dev" in lower, (
            "Dockerfile must install 'libsasl2-dev' via apt-get "
            "(needed to compile python-ldap). "
            "Spec §5.8: add 'libsasl2-dev' to the apt-get install list."
        )

    def test_dockerfile_apt_get_before_pip_install_python_ldap(self) -> None:
        """apt-get install for system deps must appear BEFORE pip install in the Dockerfile.

        WHY: If pip install runs before gcc/libldap2-dev are installed, python-ldap's
        C extension compilation fails immediately. The apt-get RUN must precede the
        pip RUN. This test validates line ordering, not just presence.
        """
        content = _dockerfile_text()
        lines = content.splitlines()

        apt_get_idx = None
        pip_install_idx = None

        for i, line in enumerate(lines):
            stripped = line.strip()
            if "apt-get" in stripped and "install" in stripped and apt_get_idx is None:
                apt_get_idx = i
            if "pip install" in stripped and pip_install_idx is None:
                pip_install_idx = i

        assert apt_get_idx is not None, (
            "Dockerfile must contain an apt-get install line for system build deps "
            "(gcc, libldap2-dev, libsasl2-dev). Not found."
        )
        assert pip_install_idx is not None, (
            "Dockerfile must contain a pip install line. Not found."
        )
        assert apt_get_idx < pip_install_idx, (
            f"apt-get install (line {apt_get_idx + 1}) must appear BEFORE "
            f"pip install (line {pip_install_idx + 1}). "
            "System build deps (gcc, libldap2-dev, libsasl2-dev) must be installed "
            "before python-ldap is compiled."
        )

    def test_dockerfile_runs_as_non_root(self) -> None:
        """Dockerfile must have a USER directive naming a non-root user.

        The USER directive must:
          1. Exist at all.
          2. Name a user that is not 'root' or '0' (running as root in a
             production container is a security violation).
          3. Appear after the last RUN/COPY instruction and before CMD,
             so the process that starts via CMD does not run as root.

        WHY: Containers running as root inherit root privileges from the host
        kernel namespace — a container escape or path-traversal vulnerability
        can gain full host access. The principle of least privilege requires
        a dedicated non-root user for every service process. Validating
        placement (after final RUN/COPY, before CMD) ensures the USER switch
        is not accidentally buried before package installs (where it would be
        overridden by a subsequent USER root in a multi-stage build).
        """
        content = _dockerfile_text()
        lines = content.splitlines()

        stripped = [line.strip() for line in lines]

        # 1. USER directive must exist.
        user_indices = [
            i for i, line in enumerate(stripped) if line.upper().startswith("USER ")
        ]
        assert user_indices, (
            f"Dockerfile must contain a USER directive to run as a non-root user. "
            f"Not found in {DOCKERFILE_PATH}. "
            "Add e.g. 'RUN adduser --disabled-password appuser' then 'USER appuser'."
        )

        last_user_idx = user_indices[-1]
        user_value = stripped[last_user_idx].split(None, 1)[1].strip()

        # 2. Named user must not be root or uid 0.
        assert user_value.lower() not in ("root", "0"), (
            f"Dockerfile USER must not be 'root' or '0'. Got: {user_value!r}. "
            "Running the service process as root violates least-privilege."
        )

        # 3. USER must appear after the last RUN/COPY and before CMD.
        cmd_indices = [
            i for i, line in enumerate(stripped) if line.upper().startswith("CMD")
        ]
        run_copy_indices = [
            i
            for i, line in enumerate(stripped)
            if line.upper().startswith("RUN ") or line.upper().startswith("COPY ")
        ]

        assert cmd_indices, (
            "Dockerfile must contain a CMD instruction (needed to verify USER placement)."
        )
        last_cmd_idx = cmd_indices[-1]

        assert last_user_idx < last_cmd_idx, (
            f"USER directive (line {last_user_idx + 1}) must appear BEFORE "
            f"CMD (line {last_cmd_idx + 1}) so the CMD process runs as the non-root user."
        )

        if run_copy_indices:
            last_run_copy_idx = run_copy_indices[-1]
            assert last_user_idx > last_run_copy_idx, (
                f"USER directive (line {last_user_idx + 1}) must appear AFTER "
                f"the last RUN/COPY (line {last_run_copy_idx + 1}) so package installs "
                "run with appropriate privileges and the final USER switch is not overridden."
            )
